### ISSUE TITLE
Set up the repository

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#1]
The `webcodingcafe/blogsuite` repository is currently empty. Some common configuration and community health files to need to be added.

## Task

Add the following files to the root of the repository:

- [x] .gitattributes
- [x] .gitignore
- [x] .editorconfig
- [x] LICENSE -> Adopt MIT license
- [x] README.md -> Short description of the project
- [x] CODE_OF_CONDUCT.md -> Adopt Contributor Covenant
- [x] CONTRIBUTING.md -> Contributor guidelines
- [x] SECURITY.md -> Security policy

Add GitHub issue templates to the repository:

- [x] .github/ISSUE_TEMPLATE/bug_report.md
- [x] .github/ISSUE_TEMPLATE/feature_request.md

Configure the issue template chooser with an additional link to GitHub Discussions of the repository:

- [x] .github/ISSUE_TEMPLATE/config.yml

Add a pull request template to the repository:

- [x] .github/pull_request_template.md

Add a changelog file:

- [x] CHANGELOG.md

## Acceptance

All files must be included and have proper content.

```
.
├── .editorconfig
├── .gitattributes
├── .gitignore
├── CHANGELOG.md
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── SECURITY.md
└── .github
    ├── ISSUE_TEMPLATE
    │   ├── bug_report.md
    │   ├── feature_request.md
    │   └── config.yml
    └── pull_request_template.md
```

### GitHub Docs

- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests

### Templates

- https://choosealicense.com/licenses/mit/
- https://www.contributor-covenant.org/
- https://editorconfig.org/
- https://keepachangelog.com/

### Documentation

- https://git-scm.com/docs/gitignore
- https://git-scm.com/docs/gitattributes
