### ISSUE TITLE
Initial repository set up

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#1]
## Task

Set up the Blogsuite project for collaboration.

- [x] Add a repository description

### Configuration files

- [x] .gitattributes
- [x] .gitignore
- [x] .editorconfig

### Informational files

- [x] README.md
- [x] LICENSE
- [x] SECURITY.md
- [x] CHANGELOG.md

### Community health files

- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md

### Templates

- [x] Bug report template
- [x] Feature request template
- [x] Configure the issue template chooser: Provide a link to Discussions
- [ ] Pull request template
