### ISSUE TITLE
Implement MySQL connection to Blogsuite using .env credentials

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#15]
## Description

Implementation of a database connection to a MySQL database in the project.

## Acceptance Criteria

- PHP code that connects to the database using the following information from .env file:
  * database host
  * username
  * password
  * database name
  * port (optional)
  * charset (optional)
- .env file must be parsed using PHP dotenv library or manually without any dependencies.
- Connection must be tested and confirmed to be working

## Tasks

- [ ] Set up .env file with database credentials
- [ ] Parse .env file to retrieve database credentials
- [ ] Connect to database using parsed credentials
- [ ] Test connection to database
- [ ] Confirm that connection works

## Notes

- Code should work on both Linux and Windows
- Add necessary error handling to ensure robustness of the implementation.
