### ISSUE TITLE
Add bootstrap.php and index.php

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#2]
The project currently has no initial application files. Bootstrapping should be the first thing to be implemented.

## Task

- [x] Create bootstrap.php (in the repository root)
- [x] Create public/index.php
- [x] Include index.php in bootstrap.php
- [x] Execute index.php on console to make sure everything works like expected.

## Acceptance

No errors when executing index.php.
