### ISSUE TITLE
Set up developer tools using Composer

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#3]
Developer tools should be used to test code quality and prevent bugs.

## Task

- [x] Create a `composer.json` file with `composer init` command
- [x] Adjust the generated setting to the project
- [x] Lock the PHP version tp `^8.2` as a requirement for the project

Install the following packages:

- [x] squizlabs/php_codesniffer
- [x] phpunit/phpunit
- [x] phpstan/phpstan
- [x] phpstan/phpstan-strict-rules
- [x] phpstan/phpstan-phpunit

Add scripts:

Scripts can be used to run the installed tools with Composer. This might be useful for CI and IDE integration.

- [x] Run PHP_Codesniffer
- [x] Run PHPStan
- [x] Run PHPUnit

Set up a testsuite for PHPUnit:

- [x] Create a `tests` directory
- [x] Create a `bootstrap.php` file insite the `tests` directory
- [x] Create a `phpunit.xml.dist` file to configure the testsuite
- [x] Add a sample unit test to test if PHPUnit works as expected

Add  additional configuration files:

- [x] Add `phpstan.neon.dist` file that includes the phpstan-strict-rules and phpstan-phpunit rulesets and sets the level to max
- [x] Add `phpcs.xml.dist` file that configures rulesets for PHP_CodeSniffer (PSR-12)

The `src`, `public` and `tests` directories should be scanned by PHPStan and PHP_Codesniffer.

## Acceptance

All developer tools are configured properly and work as expected.

## References

- https://getcomposer.org/
- https://phpunit.de/
- https://phpstan.org/
- https://github.com/phpstan/phpstan
- https://github.com/phpstan/phpstan-strict-rules
- https://github.com/phpstan/phpstan-phpunit
- https://github.com/squizlabs/PHP_CodeSniffer
