### ISSUE TITLE
Set up development tools

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#3]
## Task

Set up some useful development tool using Composer.

- [ ] Composer
- [ ] squizlabs/php_codesniffer
- [ ] phpunit/phpunit
- [ ] phpstan/phpstan
- [ ] phpstan/phpstan-strict-rules
- [ ] phpstan/phpstan-phpunit

## Reference

- https://getcomposer.org
- https://phpunit.de
- https://phpstan.org

### GitHub repositories

- https://github.com/phpstan/phpstan
- https://github.com/phpstan/phpstan-strict-rules
- https://github.com/phpstan/phpstan-phpunit
- https://github.com/squizlabs/PHP_CodeSniffer

### Packagist packages

- https://packagist.org/packages/squizlabs/php_codesniffer
- https://packagist.org/packages/phpunit/phpunit
- https://packagist.org/packages/phpstan/phpstan
- https://packagist.org/packages/phpstan/phpstan-strict-rules
- https://packagist.org/packages/phpstan/phpstan-phpunit
