### ISSUE TITLE
Set up developer tools with Composer

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#3]
## Task

Add an composer.json file to install and run developer tools with Composer on the local machine or a GitHub workflow.

### Developer tools to install

- [x] squizlabs/php_codesniffer
- [x] phpunit/phpunit
- [x] phpstan/phpstan
- [x] phpstan/phpstan-strict-rules
- [x] phpstan/phpstan-phpunit

Add the developer tools as dev dependencies and scripts to run the developer tools.

### Add configuration files

- [x] phpcs.xml.dist
- [x] phpstan.neon.dist --> include extensions!
- [x] phpunit.xml.dist

### Set up PHPUnit

- [x] /tests/constants.php --> Define path constants so they can be used in test cases
- [x] /tests/bootstrap.php --> include the Composer autoloader
- [x] Example unit test

###  Set system requirements

- [x] Add requirement for PHP version 8.2
- [x] Add requirement PDO / pdo_mysql
