### ISSUE TITLE
Add GitHub workflow

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#4]
The repository doesn't run automated tests at this point.

## Task

- [ ] Create a `php_ci.yml` file inside `.github/workflows`

The GitHub workflow should perform following actions on every pull request an push event:

- [ ] Set  `permission`  level for the workflow to `read` for `contents`
- [ ] Start the MySQL server
- [ ] Create a test database
- [ ] Install PHP 8.2
- [ ] Verify composer.json and composer.lock
- [ ] Install developer tools using Composer
- [ ] Cache packages
- [ ] Run PHP_Codesniffer using Composer script
- [ ] Run PHPStan using Composer script
- [ ] Run PHPUnit using Composer script

MySQL database credentials for the root user: username=root, password=root

## Acceptance

The GitHub action runs without errors on the main branch.

## Reference

- https://github.com/features/actions
- https://docs.github.com/en/actions
- https://github.com/shivammathur/setup-php

### Example workflow file from GitHub

```yml
name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

```

###  Example for installing PHP 8.2

```
- name: Setup PHP 8.2
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'
```
