### ISSUE TITLE
Implement PSR-4 autoloader

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#5]
The project doesn't provide autoloading of class files at this moment.

## Task

Implement an autoloader class according to the PSR-4 specification:

- [ ] Create `Autoloader` class
- [ ] Register the autoloader in bootstrap.php
- [ ] Add tests for the `Autoloader` class
- [ ] Test the autoloader by trying to instantia a temporary dummy class
- [ ] Make shure all tests pass

Requirements for the autoloader class:

- [ ] PSR-4 compliant `load` method
- [ ] Register the load method
- [ ] Unregister the autoloader

Test scenarios:

- [ ] Try to register the autoloader
- [ ] Try to unregister the autoloader
- [ ] Test if the load method loads the class file of a class being instatiated

## Acceptance

A working PSR-4 autoloader implementation that passes all tests.

## References

- https://www.php-fig.org/psr/psr-4/
- https://www.php.net/manual/en/ref.spl.php
