### ISSUE TITLE
Implement .env file parser

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#6]
## Task

Database credentials should be stored in an .env file. A parser is needed to provide the credentials for the database handler to establish a database connection.

- [ ] Create an .env.example file containing database credentials
- [ ] Add a class that reads the contents of a .env file, parses the lines and returns an array with the database credentials
- [ ] Add tests for the .env file parser class
