### ISSUE TITLE
Add index.php and bootstrap.php

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#7]
## Task

Create a bootstrap.php file that is loaded by the index.php file in the public document root directory.

- [x] public/index.php
- [x] src/bootstrap.php
- [x] Include bootstrap.php in index.php
