### ISSUE TITLE
Establish MySQL database connection using PDO

### ISSUE THREAD

**Issue by webcodingcafe** [webcodingcafe/blogsuite#7]
## Task

At this time the application does not provide a database connection. A database handler is required.

- [ ] Add a database handler class that establishes a database connection using PDO
- [ ] Establish a database connection in the bootstrap file
- [ ] Add tests
- [ ] Update the GitHub workflow to start the MySQL server and create a test database
